### ISSUE TITLE
Cop this - a starter for EF6 and MVC5

### ISSUE THREAD

**Issue by jasontaylordev** [xwipeoutx/xwipeoutx.github.io#2]
Nice post! I like how you use projections to map models to view models. Two questions: 
1) For a larger application, what design approach would you take for your unit of work and repositories (e.g. some framework, generics, ...)? 
2) Again for a larger application, would you use any mapping frameworks such as AutoMapper or continue to hand roll with projections?
Thanks again.

**Comment by xwipeoutx** [comment]
Hi @JasonGT! I've just added Disqus to the blog (about time, really), so feel free to copy your comment there if you'd prefer, and I'll do the same.

As for your questions
1) I do plan on covering this in an upcoming post, but I'll answer briefly - if your application is getting large enough to care about UoW, then you may be better suited to implementing domain driven design (DDD), and throw away unit of work completely.  For this I'll point you at: https://vaughnvernon.co/?p=879

If you don't want to go whole-hog DDD, throwing away UoW in the process, my current thinking on better UoW support is.to
a) Implement a default repository implementation that commits straight away - no UoW.
b) Repository implementation that can only be created via a factory that takes in a unit of work, and follow the dependencies all the way up.

I haven't gotten far with this idea yet though, it's still just in my head.

2) I'm against auto mapping, so I'd hand-roll all the way. It's my experience that auto mapping wastes more time in bug-fixing than it saves in trivial mapping code.

**Comment by xwipeoutx** [comment]
Thanks Jason, I've put my answer there as well - much nicer!

**Comment by jasontaylordev** [comment]
No worries mate, thanks for your response. I’m working through it now.

Cheers,

Jason
